### PR TITLE
Remove invisible properties - closes #62

### LINKED ISSUE #62: Adapter still uses unsupported invisibile properties
The visible member of properties is being [deprecated](https://github.com/WebThingsIO/gateway/issues/2467#issuecomment-739466016) in gateway 1.1.

This adapter still sets the visible member on properties, but it's no longer serialised by the gateway-addon-node library so it causes things to break.

The adapter should remove invisible properties instead, rather than passing them onto the gateway.

### PR DESCRIPTION
**Pull request by benfrancis**
Closes #62

### CODE REVIEW

**Comment by benfrancis** [comment]
Note that I'm not able to test this because I don't have any HomeKit adapters. I'd be grateful if someone could test it for me.

**Comment by freaktechnik** [comment]
This will still need the visible property set to true on the property prototype.

**Comment by benfrancis** [comment]
@freaktechnik Oh yeah, thanks.

Is this better?

**Comment by benfrancis** [comment]
BTW I tried creating a release of the add-on from my own fork for people to test, but the GitHub Action failed https://github.com/benfrancis/homekit-adapter/actions/runs/3641701291

**Comment by benfrancis** [comment]
@tim-hellhake Hi, I'm requesting a review but am unable to test this. I don't suppose you have HomeKit devices you could test this with do you?

**Comment by benfrancis** [comment]
I've manually generated a build on an linux-x64 machine with node 10 if someone wants to try and test it on their development machine, but I'm not sure if it even runs https://github.com/benfrancis/homekit-adapter/releases/tag/v0.12.0

**Comment by benfrancis** [comment]
I'm going to land this so that we can generate a build to test, in order to unblock the gateway 1.1 release.

**Pull request merged**
